services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - pb_data:/pb/pb_data
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks
    container_name: pocketbase
    ports:
      - "30164:8080"
volumes:
  pb_data:
