/// <reference path="../pb_data/types.d.ts" />
/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const collection = new Collection({
      // the id is autogenerated, but you can set a specific one if you want to
      // id:      "...",
      name:       "example",
      type:       "base",
      listRule:   null,
      viewRule:   "@request.auth.id != ''",
      createRule: "",
      updateRule: "@request.auth.id != ''",
      deleteRule: null,
      schema:     [
          {
              name:     "title",
              type:     "text",
              required: true,
              options:  {
                  max: 10,
              },
          },
          {
              name:     "user",
              type:     "relation",
              required: true,
              options:  {
                  maxSelect:     1,
                  collectionId:  "ae40239d2bc4477",
                  cascadeDelete: true,
              },
          },
      ],
      indexes: [
          "CREATE UNIQUE INDEX idx_user ON example (user)"
      ],
      options: {}
  })

  $app.dao().saveCollection(collection)
}, (db) => {
  const collection = db.dao.findCollectionByNameOrId('posts');
  return db.dao.deleteCollection(collection);
});

